### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [D-Programming-Deimos/unicorn#1]
oh, this looks very cool! do you want to send a pull req to put your repo into https://github.com/unicorn-engine/unicorn/blob/master/bindings/README ?

cheers!

**Comment by CyberShadow** [comment]
> oh, this looks very cool!

Yep, Unicorn is very cool :) These bindings are pretty straight-forward, though.

> do you want to send a pull req to put your repo into https://github.com/unicorn-engine/unicorn/blob/master/bindings/README ?

OK, done. I got the repository moved into D's official bindings org, so that it can be updated by anyone if necessary.
